### PR TITLE
maintenance: reload browser on server ready

### PR DESCRIPTION
**Pull request by Onset**
Retry-After header is unreliable, bad browser support

### CODE REVIEW

**Comment by ViliamKopecky** [comment]
Why not just use simple timeout? 

setTimeout(function(){location.reload()}, 5000)

**Comment by Onset** [comment]
@ViliamKopecky I don't like unnecessary page reloads. Page then flashes. It's hard to interact with it (scroll, select text).

**Comment by enzy** [comment]
Maintenance page doesn't return 200 by default?

**Comment by Onset** [comment]
@enzy No and it's even your code.

```
header('HTTP/1.1 503 Service Unavailable');
```

**Comment by enzy** [comment]
In that case it's good to go :dancer:

**Comment by ViliamKopecky** [comment]
ok, lets do it :)

**Pull request merged**
