### PR TITLE
update frontends

### PR DESCRIPTION
**Pull request by ViliamKopecky**

### CODE REVIEW

**Comment by ViliamKopecky** [comment]
@enzy what do you mean?

**Comment by enzy** [comment]
Like:
Synced the frontend structure with mango-cli-example

ref. https://github.com/manGoweb/mango-cli-example/commit/cfec8ee10a2b72dc773285a2ad80079c9e280693

**Comment by ViliamKopecky** [comment]
@enzy and where do you want to put this? Feel free to add your commit :)

**Comment by enzy** [comment]
In the relevant commit, ideally you should split your's into two.

**Comment by ViliamKopecky** [comment]
@enzy updated commit message, didnt split to more commits 🤠

**Pull request merged**
