### PR TITLE
Images: allow size with height auto

### PR DESCRIPTION
**Pull request by Onset**
register:
	custom_size: 600x0

### CODE REVIEW

**Comment by enzy** [comment]
Why `0`, not `auto`? :)

**Comment by Onset** [comment]
`auto` is not supported by imgproxy https://github.com/DarthSim/imgproxy/blob/master/docs/generating_the_url_basic.md#enlarge

**Comment by enzy** [comment]
My point is about semantics, not imgproxy implementation. Zero doesn't imply a meaning of a computed value for me.

**Comment by Onset** [comment]
I've created a related issue (https://github.com/manGoweb/MangoPress/issues/178). Right now I suggest keeping the neon structure similar to imgproxy as much as possible since it has a documentation (https://github.com/DarthSim/imgproxy/blob/master/docs/generating_the_url_basic.md#enlarge).

**Comment by enzy** [comment]
Okay.
As a side note: image sizes are not directly dependent on the imgproxy.

**Pull request merged**
