### PR TITLE
Pr/sprites/fix

### PR DESCRIPTION
**Pull request by Onset**
image

### CODE REVIEW

**Comment by Onset** [comment]
Fair point. Sprites are back in images.

**Comment by ViliamKopecky** [comment]
And bad Go logo is still somewhere. This needs to be destroyed. We should have some folder with correct corporate assets.

screenshot 2018-11-19 at 11 31 00

**Comment by enzy** [comment]
You either want a sprite or an image. Mixing both means bigger payload with duplicated data.

**Comment by Onset** [comment]
Makes sense too. :D

**Comment by ViliamKopecky** [comment]
@enzy mostly yeah.

And another thing is if sprites are really a good solution in the age of http2?

**Comment by Onset** [comment]
The Go logo is from `mango-cli-example`. https://github.com/manGoweb/mango-cli-example/tree/master/src/images/icons :(

**Comment by ViliamKopecky** [comment]
- if you dont need svg in sprite, you can put it directly in `images` dir
- if you need sprite, and dont need to use direct url, you dont need to use the url...

win-win :D

**Comment by enzy** [comment]
> And another thing is if sprites are really a good solution in the age of http2?

You want inline svg capabilities without need to duplicate svg data across html file. I don't know any technique from http/2 (and compatible with PHP+WP) which would help with this. Ideas?

**Pull request merged**
